export type SmilyItem = {
  id: number | string
  path: string
  thumbnailWidth: number
  thumbnailHeight: number
  width: number
  code?: number | string
}
export type SmilyKindItem = {
  id: number | string
  name: string
  path: string
  codePrefix?: string
  items: Array<SmilyItem>
}
export type SmilyData = Array<SmilyKindItem>
export const smilyData: SmilyData = [
  {
    id: 10,
    name: '兔斯基',
    path: 'too',
    items: [
      {
        id: 11,
        path: '1.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 12,
        path: '2.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 13,
        path: '3.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 14,
        path: '4.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 15,
        path: '5.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 16,
        path: '6.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 17,
        path: '7.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 18,
        path: '8.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 19,
        path: '9.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 20,
        path: '10.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 21,
        path: '11.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 22,
        path: '12.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 23,
        path: '13.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 24,
        path: '14.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 25,
        path: '15.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 26,
        path: '16.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 27,
        path: '17.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 28,
        path: '18.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 29,
        path: '19.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 30,
        path: '20.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 31,
        path: '21.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 32,
        path: '22.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 17,
        width: 50,
      },
      {
        id: 33,
        path: '23.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 34,
        path: '24.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 35,
        path: '25.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 36,
        path: '26.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 19,
        width: 50,
      },
      {
        id: 37,
        path: '27.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 38,
        path: '28.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 40,
        path: '30.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 87,
        path: '29.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 15,
        width: 50,
      },
      {
        id: 88,
        path: '31.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 89,
        path: '32.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 90,
        path: '33.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 48,
      },
    ],
  },
  {
    id: 41,
    name: '洋葱头',
    path: 'yang',
    items: [
      {
        id: 43,
        path: '2.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 44,
        path: '3.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 45,
        path: '5.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 46,
        path: '6.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 47,
        path: '7.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 49,
        path: '9.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 50,
        path: '11.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 51,
        path: '12.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 52,
        path: '13.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 53,
        path: '14.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 54,
        path: '15.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 55,
        path: '16.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 56,
        path: '17.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 57,
        path: '18.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 58,
        path: '19.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 59,
        path: '21.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 60,
        path: '23.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 61,
        path: '24.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 63,
        path: '29.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 64,
        path: '30.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 65,
        path: '31.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 66,
        path: '32.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 67,
        path: '33.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 68,
        path: '35.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 69,
        path: '36.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 70,
        path: '37.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 72,
        path: '45.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 73,
        path: '46.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 74,
        path: '47.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 75,
        path: '48.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 77,
        path: '51.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 78,
        path: '52.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 79,
        path: '53.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 80,
        path: '55.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 82,
        path: '59.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 83,
        path: '65.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 84,
        path: '66.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 85,
        path: '68.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 86,
        path: '69.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 91,
        path: '4.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 92,
        path: '8.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 93,
        path: '10.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 94,
        path: '20.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 95,
        path: '22.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 96,
        path: '25.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 97,
        path: '26.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 98,
        path: '27.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 99,
        path: '28.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 100,
        path: '34.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 101,
        path: '38.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 102,
        path: '39.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 103,
        path: '40.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 104,
        path: '41.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 105,
        path: '42.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 106,
        path: '43.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 107,
        path: '44.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 108,
        path: '49.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 109,
        path: '50.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 110,
        path: '56.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 111,
        path: '57.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 112,
        path: '58.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 113,
        path: '60.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 114,
        path: '61.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 115,
        path: '62.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 116,
        path: '63.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 117,
        path: '64.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 118,
        path: '67.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 119,
        path: '70.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 286,
        path: '201.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 287,
        path: '202.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 633,
        path: '203.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
    ],
  },
  {
    id: 209,
    name: '小蘑菇',
    path: 'mushroom',
    items: [
      {
        id: 210,
        path: '001.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 211,
        path: '002.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 212,
        path: '003.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 213,
        path: '004.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 214,
        path: '005.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 215,
        path: '006.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 216,
        path: '007.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 217,
        path: '008.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 218,
        path: '009.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 219,
        path: '010.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 220,
        path: '011.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 221,
        path: '012.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 222,
        path: '013.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 223,
        path: '014.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 224,
        path: '015.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 225,
        path: '016.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 226,
        path: '017.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 227,
        path: '018.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 228,
        path: '019.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 229,
        path: '020.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 230,
        path: '021.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 231,
        path: '022.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 232,
        path: '023.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 233,
        path: '024.gif',
        thumbnailWidth: 17,
        thumbnailHeight: 30,
        width: 28,
      },
      {
        id: 234,
        path: '025.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 235,
        path: '026.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 236,
        path: '027.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 237,
        path: '028.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 238,
        path: '029.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 239,
        path: '030.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 18,
        width: 50,
      },
      {
        id: 240,
        path: '031.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 241,
        path: '032.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 242,
        path: '033.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 243,
        path: '034.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 244,
        path: '035.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 245,
        path: '036.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 246,
        path: '037.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 247,
        path: '038.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 248,
        path: '039.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 249,
        path: '040.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 250,
        path: '041.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 251,
        path: '042.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 252,
        path: '043.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 253,
        path: '044.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 254,
        path: '045.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 255,
        path: '046.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 256,
        path: '047.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 257,
        path: '048.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 258,
        path: '049.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 259,
        path: '050.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 260,
        path: '051.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 261,
        path: '052.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 262,
        path: '053.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 263,
        path: '054.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 264,
        path: '055.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 265,
        path: '056.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 266,
        path: '057.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 267,
        path: '058.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 268,
        path: '059.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 269,
        path: '060.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 270,
        path: '061.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 271,
        path: '062.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 272,
        path: '063.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 273,
        path: '064.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 274,
        path: '065.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 275,
        path: '066.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 276,
        path: '067.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 277,
        path: '068.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 278,
        path: '069.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 279,
        path: '070.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 280,
        path: '071.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 281,
        path: '072.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 282,
        path: '073.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 283,
        path: '074.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 284,
        path: '075.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 285,
        path: '076.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
    ],
  },
  {
    id: 290,
    name: '兔耳控',
    path: 'tuerkong',
    items: [
      {
        id: 291,
        path: '1.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 292,
        path: '2.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 293,
        path: '3.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 294,
        path: '4.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 50,
      },
      {
        id: 295,
        path: '5.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 50,
      },
      {
        id: 296,
        path: '6.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 297,
        path: '7.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 298,
        path: '8.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 299,
        path: '9.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 300,
        path: '10.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 301,
        path: '11.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 302,
        path: '12.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 303,
        path: '13.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 304,
        path: '14.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 49,
      },
      {
        id: 305,
        path: '15.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 12,
        width: 50,
      },
      {
        id: 306,
        path: '16.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 307,
        path: '17.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 308,
        path: '18.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 309,
        path: '19.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 12,
        width: 50,
      },
      {
        id: 310,
        path: '20.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 311,
        path: '21.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 312,
        path: '22.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 18,
        width: 50,
      },
      {
        id: 313,
        path: '23.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 314,
        path: '24.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 315,
        path: '25.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 316,
        path: '26.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 317,
        path: '27.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 318,
        path: '28.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 319,
        path: '29.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 36,
      },
      {
        id: 320,
        path: '30.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 36,
      },
      {
        id: 321,
        path: '31.gif',
        thumbnailWidth: 21,
        thumbnailHeight: 30,
        width: 35,
      },
      {
        id: 322,
        path: '32.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 323,
        path: '33.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 48,
      },
    ],
  },
  {
    id: 324,
    name: '麻将脸',
    path: 'majiang',
    items: [
      {
        id: 325,
        path: '168.jpg.png',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 326,
        path: '161.jpg.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 34,
      },
      {
        id: 327,
        path: '155.jpg.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 328,
        path: '182.jpg.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 329,
        path: '00.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 330,
        path: '01.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 331,
        path: '02.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 332,
        path: '03.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 333,
        path: '04.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 334,
        path: '05.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 335,
        path: '06.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 336,
        path: '07.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 337,
        path: '08.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 338,
        path: '09.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 339,
        path: '10.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 340,
        path: '11.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 341,
        path: '12.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 342,
        path: '13.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 343,
        path: '14.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 344,
        path: '15.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 345,
        path: '16.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 346,
        path: '17.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 347,
        path: '18.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 348,
        path: '19.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 349,
        path: '20.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 350,
        path: '21.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 351,
        path: '22.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 352,
        path: '23.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 353,
        path: '24.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 354,
        path: '25.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 355,
        path: '26.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 36,
      },
      {
        id: 356,
        path: '27.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 357,
        path: '28.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 358,
        path: '29.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 359,
        path: '30.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 360,
        path: '31.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 361,
        path: '32.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 362,
        path: '33.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 363,
        path: '34.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 364,
        path: '35.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 365,
        path: '37.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 366,
        path: '38.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 367,
        path: '39.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 368,
        path: '40.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 369,
        path: '41.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 370,
        path: '42.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 371,
        path: '43.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 372,
        path: '44.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 373,
        path: '45.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 374,
        path: '46.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 375,
        path: '47.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 376,
        path: '48.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 377,
        path: '49.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 378,
        path: '50.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 379,
        path: '51.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 380,
        path: '52.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 381,
        path: '53.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 382,
        path: '54.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 383,
        path: '55.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 384,
        path: '56.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 385,
        path: '57.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 386,
        path: '58.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 387,
        path: '59.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 388,
        path: '60.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 389,
        path: '61.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 390,
        path: '66.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 391,
        path: '169.jpg.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 392,
        path: '74.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 393,
        path: '75.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 394,
        path: '77.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 395,
        path: '79.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 396,
        path: '80.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 397,
        path: '81.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 398,
        path: '82.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 49,
      },
      {
        id: 399,
        path: '84.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 400,
        path: '85.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 35,
      },
      {
        id: 401,
        path: '86.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 402,
        path: '87.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 403,
        path: '88.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 404,
        path: '89.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 405,
        path: '90.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 406,
        path: '91.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 407,
        path: '92.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 408,
        path: '93.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 409,
        path: '94.jpg',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 30,
      },
      {
        id: 410,
        path: '95.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 411,
        path: '96.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 412,
        path: '97.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 413,
        path: '98.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 414,
        path: '99.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 415,
        path: '156.jpg.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 416,
        path: '100.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 417,
        path: '101.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 418,
        path: '102.jpg',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 39,
      },
      {
        id: 419,
        path: '103.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 420,
        path: '104.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 35,
      },
      {
        id: 421,
        path: '105.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 422,
        path: '106.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 48,
      },
      {
        id: 423,
        path: '107.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 424,
        path: '108.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 425,
        path: '109.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 426,
        path: '110.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 427,
        path: '111.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 428,
        path: '112.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 429,
        path: '113.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 430,
        path: '114.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 431,
        path: '115.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 432,
        path: '116.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 433,
        path: '117.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 434,
        path: '118.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 435,
        path: '119.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 436,
        path: '120.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 437,
        path: '121.png',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 27,
      },
      {
        id: 438,
        path: '122.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 439,
        path: '123.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 39,
      },
      {
        id: 440,
        path: '124.jpg',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 39,
      },
      {
        id: 441,
        path: '125.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 442,
        path: '126.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 443,
        path: '127.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 444,
        path: '128.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 445,
        path: '129.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 446,
        path: '130.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 447,
        path: '131.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 26,
      },
      {
        id: 448,
        path: '132.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 449,
        path: '133.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 450,
        path: '134.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 451,
        path: '135.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 452,
        path: '136.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 453,
        path: '137.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 454,
        path: '138.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 455,
        path: '139.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 456,
        path: '140.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 457,
        path: '141.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 458,
        path: '142.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 459,
        path: '143.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 460,
        path: '144.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 461,
        path: '145.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 462,
        path: '146.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 463,
        path: '147.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 464,
        path: '148.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 465,
        path: '149.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 466,
        path: '150.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 467,
        path: '151.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 468,
        path: '152.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 469,
        path: '153.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 470,
        path: '154.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 471,
        path: '157.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 36,
      },
      {
        id: 472,
        path: '158.jpg',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 473,
        path: '159.jpg',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 474,
        path: '160.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 475,
        path: '162.jpg',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 26,
      },
      {
        id: 476,
        path: '163.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 477,
        path: '164.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 478,
        path: '165.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 479,
        path: '166.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 480,
        path: '167.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 481,
        path: '170.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 482,
        path: '171.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 483,
        path: '172.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 484,
        path: '173.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 485,
        path: '174.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 486,
        path: '175.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 487,
        path: '176.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 488,
        path: '177.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 489,
        path: '178.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 39,
      },
      {
        id: 490,
        path: '179.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 491,
        path: '180.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 492,
        path: '181.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 493,
        path: '183.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 494,
        path: '184.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 495,
        path: '185.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 496,
        path: '186.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 497,
        path: '187.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 498,
        path: '188.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 499,
        path: '189.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 500,
        path: '190.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 501,
        path: '191.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 40,
      },
      {
        id: 502,
        path: '200.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
      {
        id: 503,
        path: '201.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 32,
      },
    ],
  },
  {
    id: 634,
    name: '蛋黄脸',
    path: 'yellowface',
    items: [
      {
        id: 635,
        path: '(17).gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 46,
      },
      {
        id: 636,
        path: '(18).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 637,
        path: '(19).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 638,
        path: '(20).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 44,
      },
      {
        id: 639,
        path: '1.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 640,
        path: '(21).gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 641,
        path: '(22).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 642,
        path: '(23).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 643,
        path: '(24).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 644,
        path: '(25).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 645,
        path: '(26).gif',
        thumbnailWidth: 23,
        thumbnailHeight: 30,
        width: 38,
      },
      {
        id: 646,
        path: '(27).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 647,
        path: '(28).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 648,
        path: '(29).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 649,
        path: '(30).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 650,
        path: '(31).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 26,
        width: 50,
      },
      {
        id: 651,
        path: '(32).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 652,
        path: '(33).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 653,
        path: '(34).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 654,
        path: '(35).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 655,
        path: '(36).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 21,
        width: 50,
      },
      {
        id: 656,
        path: '(37).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 657,
        path: '(38).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 659,
        path: '(7).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 660,
        path: '(8).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 661,
        path: '(9).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 662,
        path: '(10).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 663,
        path: '(11).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 664,
        path: '(12).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 44,
      },
      {
        id: 665,
        path: '(13).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 666,
        path: '(14).gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 46,
      },
      {
        id: 667,
        path: '(15).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 1197,
        path: '(6).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 19,
        width: 50,
        code: 658,
      },
      {
        id: 1198,
        path: '(16).gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 42,
        code: 634,
      },
    ],
  },
  {
    id: 669,
    name: '暴走',
    path: 'bzmh',
    items: [
      {
        id: 670,
        path: 'bamh0.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 671,
        path: 'bamh10.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 37,
      },
      {
        id: 672,
        path: 'bamh1.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 50,
      },
      {
        id: 673,
        path: 'bamh3.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 674,
        path: 'bamh8.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 675,
        path: 'bamh9.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 676,
        path: 'bzmh002.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 677,
        path: 'bzmh003.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 678,
        path: 'bzmh004.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 45,
      },
      {
        id: 679,
        path: 'bzmh005.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 45,
      },
      {
        id: 680,
        path: 'bzmh007.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 681,
        path: 'bzmh008.gif',
        thumbnailWidth: 21,
        thumbnailHeight: 30,
        width: 35,
      },
      {
        id: 682,
        path: 'bzmh010.gif',
        thumbnailWidth: 26,
        thumbnailHeight: 30,
        width: 43,
      },
      {
        id: 683,
        path: 'bzmh012.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 684,
        path: 'bzmh013.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 685,
        path: 'bzmh017.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 686,
        path: 'bzmh018.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 687,
        path: 'bzmh019.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 688,
        path: 'bzmh020.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 689,
        path: 'bzmh021.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 690,
        path: 'bzmh022.gif',
        thumbnailWidth: 26,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 691,
        path: 'bzmh023.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 45,
      },
      {
        id: 692,
        path: 'bzmh025.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 693,
        path: 'bzmh026.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 694,
        path: 'bzmh027.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 19,
        width: 50,
      },
      {
        id: 695,
        path: 'bzmh028.gif',
        thumbnailWidth: 26,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 696,
        path: 'bzmh029.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 46,
      },
      {
        id: 697,
        path: 'bzmh032.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 698,
        path: 'bzmh033.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 699,
        path: 'bzmh035.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 45,
      },
      {
        id: 700,
        path: 'bzmh037.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 701,
        path: 'bzmh039.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 702,
        path: 'bzmh041.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 703,
        path: 'bzmh042.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 704,
        path: 'bzmh044.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 705,
        path: 'bzmh047.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 706,
        path: 'bzmh048.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 707,
        path: 'bzmh052.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 708,
        path: 'bzmh053.gif',
        thumbnailWidth: 24,
        thumbnailHeight: 30,
        width: 40,
      },
      {
        id: 709,
        path: 'bzmh057.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 710,
        path: 'bzmh059.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 50,
      },
      {
        id: 711,
        path: 'bzmh060.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 712,
        path: 'bzmh062.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 713,
        path: 'bzmh066.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 714,
        path: 'bzmh067.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 715,
        path: 'bzmh069.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 716,
        path: 'bzmh070.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 45,
      },
      {
        id: 717,
        path: 'bzmh074.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 42,
      },
      {
        id: 718,
        path: 'bzmh075.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 27,
        width: 50,
      },
      {
        id: 719,
        path: 'bzmh077.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 720,
        path: 'bzmh078.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 46,
      },
      {
        id: 721,
        path: 'bzmh079.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 722,
        path: 'bzmh081.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 723,
        path: 'bzmh084.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 26,
        width: 50,
      },
      {
        id: 724,
        path: 'bzmh085.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 725,
        path: 'bzmh086.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 41,
      },
      {
        id: 726,
        path: 'bzmh088.gif',
        thumbnailWidth: 26,
        thumbnailHeight: 30,
        width: 43,
      },
      {
        id: 727,
        path: 'bzmh091.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 26,
        width: 50,
      },
      {
        id: 728,
        path: 'bzmh092.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 50,
      },
      {
        id: 729,
        path: 'bzmh098.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 45,
      },
      {
        id: 730,
        path: 'bzmh00.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 46,
      },
      {
        id: 731,
        path: 'bzmh100.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 732,
        path: 'bzmh101.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 733,
        path: 'bzmh105.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 734,
        path: 'bzmh108.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 735,
        path: 'bzmh109.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 50,
      },
      {
        id: 736,
        path: 'bzmh110.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 737,
        path: 'bzmh113.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 738,
        path: 'bzmh116.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 739,
        path: 'bzmh117.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 740,
        path: 'bzmh118.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 741,
        path: 'bzmh119.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 742,
        path: 'bzmh120.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 21,
        width: 50,
      },
      {
        id: 743,
        path: 'bzmh121.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 744,
        path: 'bzmh123.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 745,
        path: 'bzmh125.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 746,
        path: 'bzmh127.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 747,
        path: 'bzmh128.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 748,
        path: 'bzmh129.gif',
        thumbnailWidth: 20,
        thumbnailHeight: 30,
        width: 34,
      },
      {
        id: 749,
        path: 'bzmh131.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
      {
        id: 750,
        path: 'bzmh132.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 751,
        path: 'bzmh133.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 752,
        path: 'bzmh135.gif',
        thumbnailWidth: 26,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 753,
        path: 'bzmh136.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 48,
      },
      {
        id: 754,
        path: 'bzmh138.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 755,
        path: 'bzmh140.gif',
        thumbnailWidth: 23,
        thumbnailHeight: 30,
        width: 38,
      },
      {
        id: 756,
        path: 'bzmh142.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 50,
      },
      {
        id: 757,
        path: 'bzmh144.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 758,
        path: 'bzmh145.gif',
        thumbnailWidth: 22,
        thumbnailHeight: 30,
        width: 36,
      },
      {
        id: 759,
        path: 'bzmh146.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 760,
        path: 'bzmh147.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 50,
      },
      {
        id: 761,
        path: 'bzmh150.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 47,
      },
    ],
  },
  {
    id: 762,
    name: '驴小毛',
    path: 'lu',
    items: [
      {
        id: 763,
        path: '01.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 764,
        path: '02.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 765,
        path: '03.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 766,
        path: '04.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 767,
        path: '05.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 768,
        path: '06.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 769,
        path: '07.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 770,
        path: '08.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 771,
        path: '09.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 772,
        path: '10.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 773,
        path: '11.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 774,
        path: '12.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 775,
        path: '13.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 776,
        path: '14.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 777,
        path: '15.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 778,
        path: '16.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
      {
        id: 779,
        path: '17.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 50,
      },
    ],
  },
  {
    id: 765,
    name: '阿鲁',
    path: 'alu',
    codePrefix: 'a',
    items: [
      {
        id: 1135,
        path: '22.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 41,
      },
      {
        id: 1136,
        path: '23.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1137,
        path: '24.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1138,
        path: '25.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1139,
        path: '26.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1140,
        path: '27.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 41,
      },
      {
        id: 1141,
        path: '28.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1142,
        path: '29.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1143,
        path: '30.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1144,
        path: '31.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1145,
        path: '32.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 41,
      },
      {
        id: 1146,
        path: '33.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1147,
        path: '34.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 1148,
        path: '35.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 33,
      },
      {
        id: 1149,
        path: '36.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 33,
      },
      {
        id: 1150,
        path: '37.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 41,
      },
      {
        id: 1151,
        path: '38.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 26,
        width: 35,
      },
      {
        id: 1152,
        path: '39.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1153,
        path: '40.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1154,
        path: '41.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1155,
        path: '42.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 20,
        width: 41,
      },
      {
        id: 1156,
        path: '43.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 26,
        width: 38,
      },
      {
        id: 1157,
        path: '44.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1158,
        path: '45.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1159,
        path: '46.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1160,
        path: '47.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 41,
      },
      {
        id: 1161,
        path: '48.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 1162,
        path: '49.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 1163,
        path: '50.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 41,
      },
      {
        id: 1164,
        path: '51.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 1165,
        path: '52.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1166,
        path: '53.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 20,
        width: 41,
      },
      {
        id: 1167,
        path: '54.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 29,
        width: 33,
      },
      {
        id: 1168,
        path: '55.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 42,
      },
      {
        id: 1169,
        path: '56.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 36,
      },
      {
        id: 1170,
        path: '57.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 28,
        width: 33,
      },
      {
        id: 1171,
        path: '58.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 24,
        width: 41,
      },
      {
        id: 1172,
        path: '59.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 44,
      },
      {
        id: 1173,
        path: '60.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 1174,
        path: '61.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 42,
      },
      {
        id: 1175,
        path: '62.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 42,
      },
      {
        id: 1176,
        path: '63.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 16,
        width: 50,
      },
      {
        id: 1177,
        path: '64.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 36,
      },
      {
        id: 1178,
        path: '65.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 33,
      },
      {
        id: 1179,
        path: '66.gif',
        thumbnailWidth: 29,
        thumbnailHeight: 30,
        width: 35,
      },
      {
        id: 1180,
        path: '67.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 46,
      },
      {
        id: 1181,
        path: '68.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 41,
      },
      {
        id: 1182,
        path: '69.gif',
        thumbnailWidth: 25,
        thumbnailHeight: 30,
        width: 35,
      },
      {
        id: 1183,
        path: '70.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 25,
        width: 50,
      },
      {
        id: 1184,
        path: '71.gif',
        thumbnailWidth: 27,
        thumbnailHeight: 30,
        width: 35,
      },
      {
        id: 1185,
        path: '72.gif',
        thumbnailWidth: 28,
        thumbnailHeight: 30,
        width: 34,
      },
      {
        id: 1186,
        path: '73.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 23,
        width: 41,
      },
      {
        id: 1187,
        path: '74.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 46,
      },
      {
        id: 1188,
        path: '75.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 19,
        width: 48,
      },
      {
        id: 1189,
        path: '76.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 13,
        width: 50,
      },
      {
        id: 1190,
        path: '77.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 21,
        width: 44,
      },
      {
        id: 1191,
        path: '78.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 15,
        width: 50,
      },
      {
        id: 1192,
        path: '79.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 22,
        width: 50,
      },
      {
        id: 1193,
        path: '80.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 19,
        width: 50,
      },
      {
        id: 1194,
        path: '81.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 17,
        width: 50,
      },
      {
        id: 1195,
        path: '82.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 20,
        width: 50,
      },
      {
        id: 1196,
        path: '83.gif',
        thumbnailWidth: 30,
        thumbnailHeight: 12,
        width: 50,
      },
    ],
  },
]

export type SmilyEntry = { [code: string]: string }

export type SmilyMap = { [codePrefix: string]: SmilyEntry }

export const kDefaultPrefix = 's'

function fillSmilyMap(
  entry: SmilyEntry,
  kind: SmilyKindItem,
  item: SmilyItem,
  offset?: number
) {
  let code = item.code ?? item.id
  if (offset !== undefined) {
    code = (code as number) + offset
  }
  entry[code.toString()] = `${kind.path}/${item.path}`
}

export const smilyMaps: SmilyMap = {}
smilyData.forEach((kind) => {
  const codePrefix = kind.codePrefix ?? kDefaultPrefix
  if (!smilyMaps[codePrefix]) {
    smilyMaps[codePrefix] = {}
  }
  kind.items.forEach((item) => fillSmilyMap(smilyMaps[codePrefix], kind, item))
})

export const unifiedSmilyMap: SmilyEntry = Object.assign(
  {},
  smilyMaps['s'],
  smilyMaps['a']
)

export const legacySmilyMaps: SmilyMap = {}
const 蛋黄脸 = smilyData.find((kind) => kind.name == '蛋黄脸')
if (蛋黄脸) {
  legacySmilyMaps[kDefaultPrefix] = {}
  蛋黄脸.items.forEach((item) =>
    fillSmilyMap(
      legacySmilyMaps[kDefaultPrefix],
      蛋黄脸 as SmilyKindItem,
      item,
      -460
    )
  )
}
